version: '3'

services:
   kdm_php:
      image: registry.ucann.ru/php/php7.3-fpm:latest
      volumes:
        - ./build/dev/docker/config/php/php-fpm.d:/usr/local/etc/php-fpm.d
        - ./build/dev/docker/config/nginx/ssl:/etc/nginx/ssl
        - ./build/dev/docker/config/nginx/sites-enabled/site.conf:/etc/nginx/sites-enabled/site.conf
        - ./:/app
      ports:
        - 80:80
        - 443:443
      depends_on:
        - kdm_mysql

   kdm_mysql:
      image: mysql:5.7
      volumes:

        - mysql_data:/var/lib/mysql
      ports:
        - 3306:3306
      environment:
        TZ: Europe/Moscow
        MYSQL_ROOT_PASSWORD: kdm
        MYSQL_PASSWORD: kdm
        MYSQL_USER: kdm
        MYSQL_DATABASE: kdm

volumes:
  mysql_data:
